spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mini_board?serverTimezone=Asia/Seoul
    username: root
    password: kkkimsehyen7941
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
